### ISSUE TITLE
cannot find type AK... in scope

### ISSUE THREAD

**Issue by mrprabbs** [mertguner/sound_generator#11]
<img width="876" alt="Screen Shot 2022-03-15 at 11 24 44 AM" src="https://user-images.githubusercontent.com/29307291/158424795-a76de99c-155c-479d-9fb4-d0eacf429679.png">
<img width="1108" alt="Screen Shot 2022-03-15 at 11 24 54 AM" src="https://user-images.githubusercontent.com/29307291/158424822-abe25d9f-a4b9-4299-b02c-384012de694b.png">

**Comment by siherrmann** [comment]
Easiest solution is to go into the `sound_generator.podspec` file and change line 20 to `s.dependency 'AudioKit', '<5'`. It then uses the newest compatible version 4.11.2.

**Comment by siherrmann** [comment]
Added a pull request for version restriction (as mentioned in above comment) and panning functionality in iOS.
