### ISSUE TITLE
Playing sound at a specific frequency

### ISSUE THREAD

**Issue by thammaknot** [mertguner/sound_generator#13]
First of all, thank you for creating this plugin.

When I tried to use it, I ran into one issue. Say, I want to play a sound at a constant 10kHz (sinusoidal).
When I call play(), the sound I hear is not a constant 10kHz. At the start, I think I hear a pitchy sound rising up to 10kHz...then after a fraction of a second, the sound would stabilize into the presumed 10kHz.

If I had to guess, the initial sound sounded like it was rising in frequency towards 10kHz.

Question is whether this can be avoided (and to start playing 10kHz sound from the start).

Thank you.

**Comment by mertguner** [comment]
Thank you very much for your interest in this library. I use smoothing on audio frequency transitions. If I don't use smoothing in frequency transitions, the sound will explode. But if you are going to use fixed frequency 

https://github.com/mertguner/sound_generator/blob/master/android/src/main/java/io/github/mertguner/sound_generator/generators/signalDataGenerator.java 

in this class, if you set the smothstep value to 1, the first It works at the frequency you want in the opening.

**Comment by thammaknot** [comment]
Thank you so much for the response. I'll take a look.

**Comment by louisdeveseleer** [comment]
Hi @mertguner ,
I tried changing the parameter "smoothStep" to 1, but I still get a progressive change (ramp) when the sound is played at the new frequency.
Could there be another parameter to change?
And would it be possible to have an option on the Flutter side to choose between smooth and immediate change of frequency?
