### ISSUE TITLE
    [!] CocoaPods could not find compatible versions for pod "sound_generator":

### ISSUE THREAD

**Issue by mrprabbs** [mertguner/sound_generator#8]
<img width="1218" alt="Screen Shot 2021-08-16 at 11 37 49 AM" src="https://user-images.githubusercontent.com/29307291/129598573-808a9ffe-9c0f-42c9-a548-4d427d3cd45f.png">
<img width="1164" alt="Screen Shot 2021-08-16 at 11 38 02 AM" src="https://user-images.githubusercontent.com/29307291/129598609-8b792f0f-6bc7-4ea5-80f4-0992aacd5cd7.png">
<img width="461" alt="Screen Shot 2021-08-16 at 11 38 26 AM" src="https://user-images.githubusercontent.com/29307291/129598665-4f903e9f-debc-463a-b1ec-d2f021ed280a.png">

Not sure what error I am making when importing the package.

**Comment by Paul19999** [comment]
same issues here
any idea to fix it?

**Comment by mrprabbs** [comment]
> same issues here
> 
> any idea to fix it?

Nope I just started using android instead.

**Comment by Paul19999** [comment]
I have this issues in a M1 Mac Mini
And I build few projects using sound generator normally.
However, this time I try to make my previous project as packages to import.
I encounter this error when I trying to do so.
On android it works perfectly.

**Comment by Paul19999** [comment]
Did you tried to put " pod 'AudioKit', '4.11.2' " in the pod file?
However I failed to pod update it

**Comment by Paul19999** [comment]
I fixed this issue by create another project and move my code to it～

**Comment by mrprabbs** [comment]
I tried creating a new project and copying the code over. It didn't work. What exactly did you change?

**Comment by Paul19999** [comment]
`# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end

pod 'AudioKit', '4.11.2'
`

above is my Podfile used

**Comment by anandyadav21219** [comment]
The same issue is still there not able to fix it.

**Comment by siherrmann** [comment]
Did you try my solution from issue #11 ?

**Comment by mertguner** [comment]
fiexed with v0.0.9
